config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.is_admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users

  resources :events do
  resources :registrations do
    member do
      get "steps/1" => "registrations#step1", :as => :step1
      patch "steps/1/update" => "registrations#step1_update", :as => :update_step1
      get "steps/2" => "registrations#step2", :as => :step2
      patch "steps/2/update" => "registrations#step2_update", :as => :update_step2
      get "steps/3" => "registrations#step3", :as => :step3
      patch "steps/3/update" => "registrations#step3_update", :as => :update_step3
    end
  end
  end

  resource :user

  namespace :admin do
    root "events#index"

    resources :versions do
      post :undo
    end

    resources :events do
      resources :registration_imports

      resources :registrations, :controller => "event_registrations" do
        collection do
          post :import
        end
      end

      resources :tickets, :controller => "event_tickets"
        collection do
          post :bulk_update
        end
        
        member do
          post :reorder
        end
    end

      resources :users do
        resource :profile, :controller => "user_profiles"
      end
      
    resources :categories
  end

  root "events#index"

  get "/faq" => "pages#faq"
end

app/models/event.rb
class Event < ApplicationRecord
  validates_presence_of :name, :friendly_id
  validates_uniqueness_of :friendly_id
  validates_format_of :friendly_id, :with => /\A[a-z0-9\-]+\z/

  STATUS = ["draft", "public", "private"]
  validates_inclusion_of :status, :in => STATUS

  before_validation :generate_friendly_id, :on => :create

  belongs_to :category, :optional => true
  has_many :registrations, :dependent => :destroy
  has_many :registration_imports, :dependent => :destroy
  has_many :tickets, :dependent => :destroy, :inverse_of  => :event
  accepts_nested_attributes_for :tickets, :allow_destroy => true, :reject_if => :all_blank

  scope :only_public, -> { where( :status => "public" ) }
  scope :only_available, -> { where( :status => ["public", "private"] ) }

  mount_uploader :logo, EventLogoUploader
  mount_uploaders :images, EventImageUploader
  serialize :images, JSON
  has_many :attachments, :class_name => "EventAttachment", :dependent => :destroy
  accepts_nested_attributes_for :attachments, :allow_destroy => true, :reject_if => :all_blank

  include RankedModel
  ranks :row_order

  def to_param
    self.friendly_id
  end

  protected

  def generate_friendly_id
    self.friendly_id ||= SecureRandom.uuid
  end
end

app/controllers/admin/event_registrations_controller.rb
require 'csv'
class Admin::EventRegistrationsController < AdminController
  before_action :find_event
  before_action :require_editor!

  def index
    @q = @event.registrations.ransack(params[:q])
    @registrations = @q.result.includes(:ticket).order("id DESC").page(params[:page]).per(20)
    # if params[:status].present? && Registration::STATUS.include?(params[:status])
    #   @registrations = @registrations.by_status(params[:status])
    # end

    # if params[:ticket_id].present?
    #   @registrations = @registrations.by_ticket(params[:ticket_id])
    # end

    if Array(params[:statuses]).any?
      @registrations = @registrations.by_status(params[:statuses])
    end

    if Array(params[:ticket_ids]).any?
      @registrations = @registrations.by_ticket(params[:ticket_ids])
    end

    if params[:start_on].present?
      @registrations = @registrations.where( "created_at >= ?", Date.parse(params[:start_on]).beginning_of_day )
    end

    if params[:end_on].present?
      @registrations = @registrations.where( "created_at <= ?", Date.parse(params[:end_on]).end_of_day )
    end

    if params[:registration_id].present?
      @registrations = @registrations.where( :id => params[:registration_id].split(",") )
    end

    respond_to do |format|
      format.html
      format.csv {
        @registrations = @registrations.reorder("id ASC")
        csv_string = CSV.generate do |csv|
          csv << ["報名ID", "票種", "姓名", "狀態", "Email", "報名時間"]
          @registrations.each do |r|
            csv << [r.id, r.ticket.name, r.name, t(r.status, :scope => "registration.status"), r.email, r.created_at]
          end
        end
        send_data csv_string, :filename => "#{@event.friendly_id}-registrations-#{Time.now.to_s(:number)}.csv"
      }
      format.xlsx
    end
  end

  def new
    @registration = @event.registrations.new
  end

  def create
    @registration = @event.registrations.new(registration_params)

    if @registration.save
      redirect_to admin_event_registrations_path
    else
      render "new"
    end
  end

  def edit
    @registration = @event.registrations.find_by_uuid(params[:id])
  end

  def update
    @registration = @event.registrations.find_by_uuid(params[:id])

    if @registration.update(registration_params)
      redirect_to admin_event_registrations_path
    else
      render "edit"
    end
  end

  def destroy
    @registration = @event.registrations.find_by_uuid(params[:id])
    @registration.destroy

    redirect_to admin_event_registrations_path(@event)
  end

  def import
    csv_string = params[:csv_file].read.force_encoding('utf-8')

    tickets = @event.tickets

    success = 0
    failed_records = []

    CSV.parse(csv_string) do |row|
      registration = @event.registrations.new( :status => "confirmed",
                                    :ticket => tickets.find{ |t| t.name == row[0] },
                                    :name => row[1],
                                    :email => row[2],
                                    :cellphone => row[3],
                                    :website => row[4],
                                    :bio => row[5],
                                    :created_at => Time.parse(row[6]) )

      if registration.save
        success += 1
      else
        failed_records << [row, registration]
        Rails.logger.info("#{row} ----> #{registration.errors.full_messages}")
      end
    end

    flash[:notice] = "總共匯入 #{success} 筆，失敗 #{failed_records.size} 筆"
    redirect_to admin_event_registrations_path(@event)
  end

  protected

  def find_event
    @event = Event.find_by_friendly_id!(params[:event_id])
  end

  def registration_params
    params.require(:registration).permit(:status, :ticket_id, :name, :email, :cellphone, :website, :bio)
  end
end

app/helpers/admin/event_registrations_helper.rb
module Admin::EventRegistrationsHelper
  def registration_filters(options)
    params.permit(:status, :ticket_id).merge(options)
  end
end

app/views/admin/event_registrations/_form.html.erb
<% if @registration.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% @registration.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="form-group">
  <%= f.label :ticket_id %>
  <%= f.select :ticket_id, @event.tickets.map{ |t| [t.name, t.id] }, {}, :class => "form-control" %>
</div>

<div class="form-group">
  <%= f.label :name, "姓名", :class => "control-label" %>
  <%= f.text_field :name, :class => "form-control" , :required => true , :autofocus => true %>
</div>

<div class="form-group">
 <%= f.label :email, "E-mail", :class => "control-label" %>
 <%= f.email_field :email, :class => "form-control", :required => true %>
</div>

<div class="form-group">
  <%= f.label :cellphone, "電話", :class => "control-label" %>
  <%= f.text_field :cellphone, :class => "form-control",:required => true %>
</div>

<div class="form-group">
  <%= f.label :website %>
  <%= f.url_field :website, :class => "form-control" %>
</div>

<div class="form-group">
  <%= f.label :bio %>
  <%= f.text_area :bio, :class => "form-control", :required => true %>
</div>

app/views/admin/event_registrations/edit.html.erb
<h1>Edit Rregistration</h1>

<%= form_for [:admin, @event, @registration] do |f| %>

  <%= render :partial => "form", :locals => { :f => f } %>

  <div class="form-group">
    <%= f.submit "Update", :class => "btn btn-primary" %>
    <%= link_to "Cancel", admin_event_registrations_path(@event) %>
  </div>
<% end %>

app/views/admin/event_registrations/index.html.erb
<h1><%= @event.name %> / Registrations</h1>

<p class="text-right">
<%= link_to "New Registration", new_admin_event_registration_path(@event), :class => "btn btn-primary" %>
<%= link_to "Import Registration", admin_event_registration_imports_path(@event), :class => "btn btn-primary" %>
   </p>
</p>

<% if false %>
<div class="submenu">
  <div class="btn-group">
    <%= link_to "全部 (#{@event.registrations.size})", admin_event_registrations_path(registration_filters(:status =>   nil)), :class => "btn btn-success btn-group #{(params[:status].blank?) ? "active" : ""}" %>
    <% Registration::STATUS.each do |s| %>
      <%= link_to t(s, :scope => "registration.status") + " (#{@event.registrations.by_status(s).size})",   admin_event_registrations_path(registration_filters(:status => s)), :class => "btn btn-success btn-group #{(  params[:status] == s) ? "active" : ""}" %>
      <% end %>
  </div>

  <div class="btn-group">
    <%= link_to "全部 (#{@event.registrations.size})", admin_event_registrations_path(registration_filters(:ticket_id =>   nil)), :class => "btn btn-default btn-group #{(params[:ticket_id].blank?) ? "active" : ""}" %>
    <% @event.tickets.each do |t| %>
      <%= link_to t.name + " (#{@event.registrations.by_ticket(t).size})", admin_event_registrations_path(  registration_filters(:ticket_id => t.id)), :class => "btn btn-default btn-group #{(params[:ticket_id].to_i == t.id)   ? "active" : ""}" %>
    <% end %>
  </div>
</div>
<% end %>

  <%= search_form_for @q, :url => admin_event_registrations_path(@event) do |f| %>

    <p><%= f.search_field :name_cont, :placeholder => "姓名", :class => "form-control" %></p>
    <p><%= f.search_field :email_cont, :placeholder => "E-mail", :class => "form-control" %></p>
  <p><%= text_field_tag :registration_id, params[:registration_id], :placeholder => "報名編號，可用,區隔", :class => "form-control" %></p>
  <p><% Registration::STATUS.each do |s| %>
    <label><%= check_box_tag "statuses[]", s, Array(params[:statuses]).include?(s) %> <%= t(s, :scope => + "registration.status") %> (<%= @event.registrations.by_status(s).size %>)</label>
  <% end %></p>

  <p><% @event.tickets.each do |t| %>
    <label><%= check_box_tag "ticket_ids[]", t.id, Array(params[:ticket_ids]).include?(t.id.to_s) %> <%= t.name %> (<%= + @event.registrations.where( :ticket_id => t.id ).size %>)</label>
  <% end %></p>

  <p>
    報名日期：<%= date_field_tag :start_on, params[:start_on] %>～<%= date_field_tag :end_on, params[:end_on] %>
  </p>

  <p class="text-right">
    <%= submit_tag "送出篩選", :class => "btn btn-primary" %>
  </p>
<% end %>

<table class="table">
<tr>
  <th>ID</th>
  <th>Ticket</th>
  <th>Name</th>
  <th>Status</th>
  <th>E-mail</th>
  <th>建立時間</th>
  <th>Actions</th>
</tr>
<% @registrations.each do |registration| %>
  <tr>
    <td><%= registration.id %></td>
    <td><%= registration.ticket.name %></td>
    <td><%= registration.name %></td>
    <td><%= t( registration.status, :scope => "registration.status") %></td>
    <td><%= registration.email %></td>
    <td><%= registration.created_at %></td>
    <td>
      <%= link_to "Edit", edit_admin_event_registration_path(@event, registration), :class => "btn btn-default" %>
      <%= link_to "Delete", admin_event_registration_path(@event, registration), :method => "delete", :data => { :confirm => "Are you sure?" }, :class => "btn btn-danger" %>
  </tr>
<% end %>
</table>

<%= paginate @registrations %>

<p>
  <%= link_to "匯出 CSV", admin_event_registrations_path(:format => :csv), :class => "btn btn-default" %>
  <%= link_to "匯出 Excel", admin_event_registrations_path(:format => :xlsx), :class => "btn btn-default" %>
</p>

<hr>

<%= form_tag import_admin_event_registrations_path(@event), :multipart => true do %>
  <p><%= file_field_tag "csv_file" %></p>
  <p><%= submit_tag "匯入CSV", :class => "btn btn-danger" %></p>
<% end %>

app/views/admin/event_registrations/new.html.erb
<h1>New Registration</h1>

<%= form_for [:admin, @event, @registration] do |f| %>

  <%= render :partial => "form", :locals => { :f => f } %>

  <div class="form-group">
    <%= f.submit "Create", :class => "btn btn-primary" %>
    <%= link_to "Cancel", admin_event_registrations_path(@event) %>
  </div>
<% end %>