config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.is_admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users

  resources :events do
  resources :registrations do
    member do
      get "steps/1" => "registrations#step1", :as => :step1
      patch "steps/1/update" => "registrations#step1_update", :as => :update_step1
      get "steps/2" => "registrations#step2", :as => :step2
      patch "steps/2/update" => "registrations#step2_update", :as => :update_step2
      get "steps/3" => "registrations#step3", :as => :step3
      patch "steps/3/update" => "registrations#step3_update", :as => :update_step3
    end
  end
  end

  resource :user

  namespace :admin do
    root "events#index"

    resources :versions do
      post :undo
    end

    resources :events do
      resources :registration_imports

      resources :registrations, :controller => "event_registrations" do
        collection do
          post :import
        end
      end

      resources :tickets, :controller => "event_tickets"
        collection do
          post :bulk_update
        end
        
        member do
          post :reorder
        end
    end

      resources :users do
        resource :profile, :controller => "user_profiles"
      end
      
    resources :categories
  end

  root "events#index"

  get "/faq" => "pages#faq"
end

app/models/event.rb
class Event < ApplicationRecord
  validates_presence_of :name, :friendly_id
  validates_uniqueness_of :friendly_id
  validates_format_of :friendly_id, :with => /\A[a-z0-9\-]+\z/

  STATUS = ["draft", "public", "private"]
  validates_inclusion_of :status, :in => STATUS

  before_validation :generate_friendly_id, :on => :create

  belongs_to :category, :optional => true
  has_many :registrations, :dependent => :destroy
  has_many :registration_imports, :dependent => :destroy
  has_many :tickets, :dependent => :destroy, :inverse_of  => :event
  accepts_nested_attributes_for :tickets, :allow_destroy => true, :reject_if => :all_blank

  scope :only_public, -> { where( :status => "public" ) }
  scope :only_available, -> { where( :status => ["public", "private"] ) }

  mount_uploader :logo, EventLogoUploader
  mount_uploaders :images, EventImageUploader
  serialize :images, JSON
  has_many :attachments, :class_name => "EventAttachment", :dependent => :destroy
  accepts_nested_attributes_for :attachments, :allow_destroy => true, :reject_if => :all_blank

  include RankedModel
  ranks :row_order

  def to_param
    self.friendly_id
  end

  protected

  def generate_friendly_id
    self.friendly_id ||= SecureRandom.uuid
  end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < AdminController
  before_action :require_editor!

  def index
    @events = Event.rank(:row_order).all
  end

  def show
    @event = Event.find_by_friendly_id!(params[:id])

    colors = ['rgba(255, 99, 132, 0.2)',
              'rgba(54, 162, 235, 0.2)',
              'rgba(255, 206, 86, 0.2)',
              'rgba(75, 192, 192, 0.2)',
              'rgba(153, 102, 255, 0.2)',
              'rgba(255, 159, 64, 0.2)'
              ]

    ticket_names = @event.tickets.map { |t| t.name }

    status_colors = { "confirmed" => "#FF6384",
                      "pending" => "#36A2EB"}

    @data1 = {
        labels: ticket_names,
        datasets: Registration::STATUS.map do |s|
          {
            label: I18n.t(s, :scope => "registration.status"),
            data: @event.tickets.map{ |t| t.registrations.by_status(s).count },
            backgroundColor: status_colors[s],
            borderWidth: 1
          }
        end
    }

    @data2 = {
        labels: ticket_names,
        datasets: [{
            label: '# of Amount',
            data:  @event.tickets.map{ |t| t.registrations.by_status("confirmed").count * t.price },
            backgroundColor: colors,
            borderWidth: 1
        }]
    }

    if @event.registrations.any?
      dates = (@event.registrations.order("id ASC").first.created_at.to_date..Date.today).to_a

      @data3 = {
        labels: dates,
        datasets: Registration::STATUS.map do |s|
          {
            :label => I18n.t(s, :scope => "registration.status"),
            :data => dates.map{ |d|
              @event.registrations.by_status(s).where( "created_at >= ? AND created_at <= ?", d.beginning_of_day, d.end_of_day).count
            },
            borderColor: status_colors[s]
          }
        end
      }
    end
  end

  def new
    @event = Event.new
    @event.tickets.build
    @event.attachments.build
  end

  def create
    @event = Event.new(event_params)

    if @event.save
      redirect_to admin_events_path
    else
      render "new"
    end
  end

  def edit
    @event = Event.find_by_friendly_id!(params[:id])
    @event.tickets.build if @event.tickets.empty?
    @event.attachments.build if @event.attachments.empty?
  end

  def update
    @event = Event.find_by_friendly_id!(params[:id])

    if @event.update(event_params)
      redirect_to admin_events_path
    else
      render "edit"
    end
  end

  def destroy
    @event = Event.find_by_friendly_id!(params[:id])
    @event.destroy

    redirect_to admin_events_path
  end

  def bulk_update
    total = 0
    Array(params[:ids]).each do |event_id|
      event = Event.find(event_id)

      if params[:commit] == I18n.t(:bulk_update)
        event.status = params[:event_status]
        if event.save
          total += 1
        end
      elsif params[:commit] == I18n.t(:bulk_delete)
        event.destroy
        total += 1
      end
    end

    flash[:notice] = "成功完成 #{total} 筆"
    redirect_to admin_events_path
  end

  def reorder
    @event = Event.find_by_friendly_id!(params[:id])
    @event.row_order_position = params[:position]
    @event.save!

    respond_to do |format|
      format.html { redirect_to admin_events_path }
      format.json { render :json => { :message => "ok" }}
    end
  end

  protected

  def event_params
    params.require(:event).permit(:name, :logo, :remove_logo, :remove_images, :description, :friendly_id, :status, :category_id, :images => [], :tickets_attributes => [:id, :name, :description, :price, :_destroy], :attachments_attributes => [:id, :attachment, :description, :_destroy])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.only_public.rank(:row_order).all
  end

  def show
    @event = Event.only_available.find_by_friendly_id!(params[:id])
  end
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/admin/events/_form.html.erb
<% if @event.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@event.errors.count, "error") %> prohibited this person from being saved:</h2>

    <ul>
    <% @event.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, :class => "form-control" %>
</div>

<div class="form-group">
  <%= f.label :description %>
  <%= f.cktext_area :description, ckeditor: { language: 'zh-TW'} %>
</div>

<div class="form-group">
  <%= f.label :status %>
  <div class="btn-group" data-toggle="buttons">
    <% Event::STATUS.each do |status| %>
      <label class="btn btn-default <%= (status == f.object.status)? 'active' : '' %>">
        <%= f.radio_button :status, status %>
        <%= t(status, :scope => "event.status") %>
      </label>
    <% end %>
  </div>
</div>

<div class="form-group">
  <%= f.label :friendly_id %>
  <%= f.text_field :friendly_id, :required => true, :class => "form-control" %>
  <p class="help-block">限小寫英數字及橫線，將為網址的一部分</p>
</div>

<div class="form-group">
  <%= f.label :category_id %>
  <%= f.select :category_id, Category.all.map{ |c| [c.name, c.id] }, {}, :class => "form-control" %>
</div>

<div class="form-group">
  <%= f.label :logo %>
  <%= f.file_field :logo, :class => "form-control" %>
  <% if f.object.logo.present? %>
    <label>
      <%= f.check_box :remove_logo %> 刪除圖片
    </label>
      <%= link_to f.object.logo.filename, f.object.logo.url, :target => "_blank" %>
  <% end %>
</div>

<div class="form-group">
  <%= f.label :images %>
  <%= f.file_field :images, :multiple => true, :class => "form-control" %>
  <% if f.object.images.present? %>
    <label>
      <%= f.check_box :remove_images %> 刪除圖片
    </label>
    <% f.object.images.each do |i| %>
      <%= link_to i.filename, i.url, :target => "_blank" %>
    <% end %>
  <% end %>
</div>

<%= f.nested_fields_for :attachments do |ff| %>
  <fieldset style="border-left: 5px solid #bbb; margin-bottom: 10px; padding: 10px;">
    <legend>Attachment</legend>
    <div class="form-group">
      <%= ff.label :attachment %>
      <%= ff.file_field :attachment, :class => "form-control" %>
      <% if ff.object.attachment.present? %>
        已上傳檔案 <%= link_to ff.object.description, ff.object.attachment.url, :target => "_blank" %>
      <% end %>
    </div>

    <div class="form-group">
      <%= ff.label :description %>
      <%= ff.text_field :description, :class => "form-control" %>
    </div>

    <%= ff.remove_nested_fields_link "移除這個檔案", :class => "btn btn-danger" %>
  </fieldset>
<% end %>
<p class="text-right">
  <%= f.add_nested_fields_link :attachments, "新增檔案", :class => "btn btn-default" %>
</p>

<%= f.nested_fields_for :tickets do |ff| %>
  <fieldset style="border-left: 5px solid #bbb; margin-bottom: 10px; padding: 10px;">
    <legend>Ticket</legend>
    <div class="form-group">
      <%= ff.label :name %>
      <%= ff.text_field :name, :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= ff.label :price %>
      <%= ff.number_field :price, :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= ff.label :description %>
      <%= ff.text_area :description, :class => "form-control" %>
    </div>
  </fieldset>
  <%= ff.remove_nested_fields_link "移除票種", :class => "btn btn-danger" %>
<% end %>
<p class="text-right">
  <%= f.add_nested_fields_link :tickets, "新增票種", :class => "btn btn-default" %>
</p>

<script>
  $("#event_category_id").select2( { theme: "bootstrap"} );
</script>

app/views/admin/events/edit.html.erb
<h1>Edit Event</h1>

<%= form_for [:admin, @event] do |f| %>

  <%= render :partial => "form", :locals => { :f => f } %>

  <div class="form-group">
    <%= f.submit "Update", :class => "btn btn-primary" %>
    <%= link_to "Cancel", admin_events_path %>
  </div>
<% end %>

app/views/admin/events/index.html.erb
<h1><%= t("admin.event_list") %></h1>

<p class="text-right">
<%= link_to "New Event", new_admin_event_path, :class => "btn btn-primary" %>
</p>

<%= form_tag bulk_update_admin_events_path, :class => "form-inline" do %>
<table class="table">
<thead>
<tr>
  <th><%= check_box_tag "全選", "1", false, :id => "toggle_all" %></th>
  <th>Event Name</th>
  <th>Actions</th>
</tr>
</thead>
<tbody class="sortable">
<% @events.each do |event| %>
  <tr data-reorder-url="<%= reorder_admin_event_path(event) %>">
    <td>
      <%= check_box_tag "ids[]", event.id %>
    </td>
    <td>
      <span class="sortable_icon">☰</span>
      <%= link_to event.name, admin_event_path(event) %>
    </td>
    <td>
      <%= link_to "置頂", reorder_admin_event_path(event, position: "first"), method: :post, class: "btn btn-default" %>
      <%= link_to "置底", reorder_admin_event_path(event, position: "last"), method: :post, class: "btn btn-default" %>
      <%= link_to "Registrations", admin_event_registrations_path(event), :class => "btn btn-default" %>
      <%= link_to "Tickets", admin_event_tickets_path(event), :class => "btn btn-default" %>
      <%= link_to "Edit", edit_admin_event_path(event), :class => "btn btn-default" %>
      <%= link_to "Delete", admin_event_path(event), :method => "delete", :data => { :confirm => "Are you sure?" }, :class => "btn btn-danger" %>
  </tr>
<% end %>
</tbody>
</table>
  <p>
  <%= select_tag :event_status, options_for_select( Event::STATUS.map{ |s| [t(s, :scope => "event.status"), s] }), :class => "form-control" %>

  <%= submit_tag t(:bulk_update), :class => "btn btn-primary" %>
  <%= submit_tag t(:bulk_delete), :class => "btn btn-danger", :data => { :confirm => "Are you sure?" } %>
  </p>
<% end %>

<script>
  $("#toggle_all").click(function(){
    if ( $(this).prop("checked") ) {
      $("input[name='ids[]']").prop("checked", true);
    } else {
      $("input[name='ids[]']").prop("checked", false);
    }
  })

  $( ".sortable" ).sortable({
    axis: 'y',       // 限制只能上下拖拉
    items: 'tr',     // 拖拉整個 tr
    cursor: 'move',  // 變更拖拉時的 icon
    handle: ".sortable_icon",  // 限制只有點 ☰ 才能拖拉
    stop: function(e, ui){     // 當拖拉結束時，會調用這個方法
      ui.item.children('td').effect('highlight', {}, 1000)
    },
    update: function(e, ui) {   // 當拖拉結束並且 DOM 上的位置改變時，會調用這個方法
      reorder_url = ui.item.data('reorder-url')
      position = ui.item.index()  // 取得順序
      $.ajax({
        type: 'POST',
        url: reorder_url,
        dataType: 'json',
        data: { position: position }
      })
    }
  });
</script>

app/views/admin/events/new.html.erb
<h1>New Event</h1>

<%= form_for [:admin, @event] do |f| %>

  <%= render :partial => "form", :locals => { :f => f } %>

  <div class="form-group">
    <%= f.submit "Create", :class => "btn btn-primary" %>
    <%= link_to "Cancel", admin_events_path %>
  </div>
<% end %>

app/views/admin/events/show.html.erb
<script src="//cdn.bootcss.com/Chart.js/2.5.0/Chart.bundle.min.js"></script>

<h1><%= @event.name %></h1>

<p>
  <%= link_to "打開前台", event_path(@event), :target => "_blank", :class => "btn btn-primary" %>
</p>

<%= sanitize @event.description %>

<canvas id="myChart1" width="400" height="200"></canvas>
<script>
var ctx1 = document.getElementById("myChart1");
var myChart1 = new Chart(ctx1, {
    type: 'bar',
    data: <%= raw @data1.to_json %>,
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});
</script>

<hr>

<canvas id="myChart2" width="400" height="200"></canvas>
<script>
var ctx2 = document.getElementById("myChart2");
var myChart2 = new Chart(ctx2, {
    type: 'bar',
    data: <%= raw @data2.to_json %>,
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});
</script>

<hr>

<canvas id="myChart3" width="400" height="200"></canvas>
<script>
var ctx3 = document.getElementById("myChart3");
var myChart3 = new Chart(ctx3, {
    type: 'line',
    data: <%= raw @data3.to_json %>,
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});
</script>