config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.is_admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users

  resources :events do
  resources :registrations do
    member do
      get "steps/1" => "registrations#step1", :as => :step1
      patch "steps/1/update" => "registrations#step1_update", :as => :update_step1
      get "steps/2" => "registrations#step2", :as => :step2
      patch "steps/2/update" => "registrations#step2_update", :as => :update_step2
      get "steps/3" => "registrations#step3", :as => :step3
      patch "steps/3/update" => "registrations#step3_update", :as => :update_step3
    end
  end
  end

  resource :user

  namespace :admin do
    root "events#index"

    resources :versions do
      post :undo
    end

    resources :events do
      resources :registration_imports

      resources :registrations, :controller => "event_registrations" do
        collection do
          post :import
        end
      end

      resources :tickets, :controller => "event_tickets"
        collection do
          post :bulk_update
        end
        
        member do
          post :reorder
        end
    end

      resources :users do
        resource :profile, :controller => "user_profiles"
      end
      
    resources :categories
  end

  root "events#index"

  get "/faq" => "pages#faq"
end

app/controllers/admin/event_tickets_controller.rb
class Admin::EventTicketsController < AdminController
  before_action :find_event
  before_action :require_editor!

  def index
    @tickets = @event.tickets
  end

  def new
    @ticket = @event.tickets.new
  end

  def create
    @ticket = @event.tickets.new(ticket_params)

    if @ticket.save
      redirect_to admin_event_tickets_path(@event)
    else
      render "new"
    end
  end

  def edit
    @ticket = @event.tickets.find(params[:id])
  end

  def update
    @ticket = @event.tickets.find(params[:id])

    if @ticket.update(ticket_params)
      redirect_to admin_event_tickets_path(@event)
    else
      render "edit"
    end
  end

  def destroy
    @ticket = @event.tickets.find(params[:id])
    @ticket.destroy

    redirect_to admin_event_tickets_path(@event)
  end

  protected

  def find_event
    @event = Event.find_by_friendly_id!(params[:event_id])
  end

  def ticket_params
    params.require(:ticket).permit(:name, :price, :description)
  end
end

app/helpers/admin/event_tickets_helper.rb
module Admin::EventTicketsHelper
end

app/views/admin/event_tickets/_form.html.erb
<% if @ticket.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% @ticket.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, :class => "form-control" %>
</div>

<div class="form-group">
  <%= f.label :price %>
  <%= f.number_field :price, :class => "form-control" %>
</div>

<div class="form-group">
  <%= f.label :description %>
  <%= f.text_area :description, :class => "form-control" %>
</div>

app/views/admin/event_tickets/edit.html.erb
<h1>Edit Ticket</h1>

<%= form_for [:admin, @event, @ticket] do |f| %>

  <%= render :partial => "form", :locals => { :f => f } %>

  <div class="form-group">
    <%= f.submit "Update", :class => "btn btn-primary" %>
    <%= link_to "Cancel", admin_event_tickets_path(@event) %>
  </div>
<% end %>

app/views/admin/event_tickets/index.html.erb
<h1><%= @event.name %> / Tickets</h1>

<p class="text-right">
<%= link_to "New Ticket", new_admin_event_ticket_path(@event), :class => "btn btn-primary" %>
</p>

<table class="table">
<tr>
  <th>Name</th>
  <th>Price</th>
  <th>Description</th>
  <th>Actions</th>
</tr>
<% @tickets.each do |ticket| %>
  <tr>
    <td><%= ticket.name %></td>
    <td><%= ticket.price %></td>
    <td><%= simple_format ticket.description %></td>
    <td>
      <%= link_to "Edit", edit_admin_event_ticket_path(@event, ticket), :class => "btn btn-default" %>
      <%= link_to "Delete", admin_event_ticket_path(@event, ticket), :method => "delete", :data => { :confirm => "Are you sure?" }, :class => "btn btn-danger" %>
  </tr>
<% end %>
</table>

app/views/admin/event_tickets/new.html.erb
<h1>New Ticket</h1>

<%= form_for [:admin, @event, @ticket] do |f| %>

  <%= render :partial => "form", :locals => { :f => f } %>

  <div class="form-group">
    <%= f.submit "Create", :class => "btn btn-primary" %>
    <%= link_to "Cancel", admin_event_tickets_path(@event) %>
  </div>
<% end %>