config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.is_admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users

  resources :events do
  resources :registrations do
    member do
      get "steps/1" => "registrations#step1", :as => :step1
      patch "steps/1/update" => "registrations#step1_update", :as => :update_step1
      get "steps/2" => "registrations#step2", :as => :step2
      patch "steps/2/update" => "registrations#step2_update", :as => :update_step2
      get "steps/3" => "registrations#step3", :as => :step3
      patch "steps/3/update" => "registrations#step3_update", :as => :update_step3
    end
  end
  end

  resource :user

  namespace :admin do
    root "events#index"

    resources :versions do
      post :undo
    end

    resources :events do
      resources :registration_imports

      resources :registrations, :controller => "event_registrations" do
        collection do
          post :import
        end
      end

      resources :tickets, :controller => "event_tickets"
        collection do
          post :bulk_update
        end
        
        member do
          post :reorder
        end
    end

      resources :users do
        resource :profile, :controller => "user_profiles"
      end
      
    resources :categories
  end

  root "events#index"

  get "/faq" => "pages#faq"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :events
end

app/models/event.rb
class Event < ApplicationRecord
  validates_presence_of :name, :friendly_id
  validates_uniqueness_of :friendly_id
  validates_format_of :friendly_id, :with => /\A[a-z0-9\-]+\z/

  STATUS = ["draft", "public", "private"]
  validates_inclusion_of :status, :in => STATUS

  before_validation :generate_friendly_id, :on => :create

  belongs_to :category, :optional => true
  has_many :registrations, :dependent => :destroy
  has_many :registration_imports, :dependent => :destroy
  has_many :tickets, :dependent => :destroy, :inverse_of  => :event
  accepts_nested_attributes_for :tickets, :allow_destroy => true, :reject_if => :all_blank

  scope :only_public, -> { where( :status => "public" ) }
  scope :only_available, -> { where( :status => ["public", "private"] ) }

  mount_uploader :logo, EventLogoUploader
  mount_uploaders :images, EventImageUploader
  serialize :images, JSON
  has_many :attachments, :class_name => "EventAttachment", :dependent => :destroy
  accepts_nested_attributes_for :attachments, :allow_destroy => true, :reject_if => :all_blank

  include RankedModel
  ranks :row_order

  def to_param
    self.friendly_id
  end

  protected

  def generate_friendly_id
    self.friendly_id ||= SecureRandom.uuid
  end
end

app/models/event_attachment.rb
class EventAttachment < ApplicationRecord
  mount_uploader :attachment, EventAttachmentUploader
  belongs_to :event
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :memberships
  has_many :users, :through => :memberships
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/profile.rb
class Profile < ApplicationRecord
  has_one :user
end

app/models/registration.rb
class Registration < ApplicationRecord
  STATUS = ["pending", "confirmed", "cancalled"]
  validates_inclusion_of :status, :in => STATUS
  validates_presence_of :status, :ticket_id

  belongs_to :event
  belongs_to :ticket
  belongs_to :user, :optional => true

  before_validation :generate_uuid, :on => :create

  attr_accessor :current_step
  validates_presence_of :name, :email, :cellphone, :if => :should_validate_basic_data?
  validates_presence_of :name, :email, :cellphone, :bio, :if => :should_validate_all_data?
  validate :check_event_status, :on => :create

  scope :by_status, ->(s){ where( :status => s ) }
  scope :by_ticket, ->(t){ where( :ticket_id => t ) }
  has_paper_trail

  def to_param
    self.uuid
  end

  protected

  def generate_uuid
    self.uuid = SecureRandom.uuid
  end

  def should_validate_basic_data?
    current_step == 2
  end

  def should_validate_all_data?
    current_step == 3 || status == "confirmed"
  end

  def check_event_status
    if self.event.status == "draft"
      errors.add(:base, "活動尚未開放報名")
    end
  end
end

app/models/registration_import.rb
require 'csv'
class RegistrationImport < ApplicationRecord
  mount_uploader :csv_file, RegistrationImportCsvUploader

  validates_presence_of :csv_file

  belongs_to :event
  belongs_to :user

  serialize :error_messages, JSON

  def process!
    csv_string = self.csv_file.read.force_encoding('utf-8')
    tickets = self.event.tickets

    success = 0
    failed_records = []

    CSV.parse(csv_string) do |row|
      registration = self.event.registrations.new( :status => "confirmed",
                                   :ticket => tickets.find{ |t| t.name == row[0] },
                                   :name => row[1],
                                   :email => row[2],
                                   :cellphone => row[3],
                                   :website => row[4],
                                   :bio => row[5],
                                   :created_at => Time.parse(row[6]) )

      if registration.save
        success += 1
      else
        failed_records << [row, registration.errors.full_messages]
      end
    end

    self.status = "imported"
    self.success_count = success
    self.total_count = success + failed_records.size
    self.error_messages = failed_records
    self.save!
  end
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  validates_presence_of :name, :price
  belongs_to :event
  has_many :registrations
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :registrations
  has_many :memberships
  has_many :groups, :through => :memberships
  has_one :profile
  accepts_nested_attributes_for :profile

  ROLES = ["admin", "editor"]

  def display_name
    self.email.split("@").first
  end

  def is_admin?
    self.role == "admin"
  end

  def is_editor?
    ["admin", "editor"].include?(self.role)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  before_action :require_admin!

  def index
    @users = User.includes(:groups).all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
        redirect_to admin_users_path
    else
      render "edit"
    end
  end

  protected

  def user_params
    params.require(:user).permit(:email, :role, :group_ids => [])
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  layout "admin"

  protected

  def require_admin!
    unless current_user.is_admin?
      flash[:alert] = "您的權限不足"
      redirect_to root_path
    end
  end

  def require_editor!
    unless current_user.is_editor?
      flash[:alert] = "您的權限不足"
      redirect_to root_path
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.only_public.rank(:row_order).all
  end

  def show
    @event = Event.only_available.find_by_friendly_id!(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_user

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "修改成功"
      redirect_to edit_user_path
    else
      render "edit"
    end
  end

  protected

  def find_user
    @user = current_user
    @user.create_profile unless @user.profile
  end

  def user_params
    params.require(:user).permit(:time_zone, :profile_attributes => [:id, :legal_name, :birthday, :location, :education, :occupation, :bio, :specialty] )
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/users/edit.html.erb
<h1>Edit User</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for [:admin, @user] do |f| %>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :role %>
    <%= f.select :role, User::ROLES.map{ |x| [t(x, :scope => "user.role"), x] }, { :include_blank => true }, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit "Update", :class => "btn btn-primary" %>
    <%= link_to "Cancel", admin_users_path %>
  </div>

  <div class="form-group">
    <%= f.label :group_ids %>
    <%= f.select :group_ids, Group.all.map{ |g| [g.name, g.id] }, {}, :multiple => true, :class => "form-control" %>
  </div>
<% end %>

<script>
  $("#user_group_ids").select2()
</script>

app/views/admin/users/index.html.erb
<h1>Admin Users</h1>

<table class="table">
<tr>
  <th>ID</th>
  <th>Email</th>
  <th>Groups</th>
  <th>Actions</th>
</tr>
<% @users.each do |user| %>
  <tr>
    <td><%= user.id %></td>
    <td><%= user.email %></td>
    <td>
      <% user.groups.each do |g| %>
        <%= g.name %><br>
      <% end %>
    </td>
    <td><%= link_to "Edit", edit_admin_user_path(user), :class => "btn btn-default" %></td>
    <td><%= link_to "Edit Profile", edit_admin_user_profile_path(user), :class => "btn btn-default" %></td>
  </tr>
<% end %>
</table>

app/views/users/edit.html.erb
<h2>Edit User</h2>

<%= form_for @user do |f| %>
  <div class="form-group">
    <%= f.label :time_zone %>
    <%= f.time_zone_select :time_zone %>
  </div>

  <%= f.fields_for :profile do |ff| %>
    <div class="form-group">
      <%= ff.label :legal_name %>
      <%= ff.text_field :legal_name, :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= ff.label :birthday %>
      <%= ff.text_field :birthday, :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= ff.label :location %>
      <%= ff.text_field :location, :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= ff.label :education %>
      <%= ff.text_field :education, :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= ff.label :occupation %>
      <%= ff.text_field :occupation, :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= ff.label :bio %>
      <%= ff.text_area :bio, :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= ff.label :specialty %>
      <%= ff.text_area :specialty, :class => "form-control" %>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.submit "Save", :class => "btn btn-primary" %>
  </div>
<% end %>

<script>
  $("#user_profile_attributes_birthday").datepicker({ format: "yyyy-mm-dd", language: "<%= I18n.locale %>" });
</script>

app/views/users/show.html.erb
<h1>我的個人資料</h1>

<p>Email: <%= @user.email %></p>
<p>Timezone: <%= @user.time_zone %></p>
<p>Birthday: <%= @user.profile.birthday %></p>
<p>Bio: <%= simple_format @user.profile.bio %></p>